Use Gradle wrapper v.5.6.4.
+ Changelog: https://docs.gradle.org/5.6.4/release-notes.html.
+ An update to Gradle wrapper v.6.x is avoided at this point in time.
  It causes the following error when using the library artifacts from
  an application project.

  Error: "roadsigns-x.x.x.aar: Resource and asset merger:
  The file name must end with .xml"